notifications:
  slack: cantare:SsYWkf9NP9EjatjzVgUhuJjy
language: node_js
before_script:
  - npm run build
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
node_js:
  - "0.10"
